# Generated by Django 6.1 on 2026-08-21 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Categoría de Repuesto',
                'verbose_name_plural': 'Categorías de Repuesto',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('pais_origen', models.CharField(blank=True, max_length=100)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('nombre', models.CharField(max_length=100)),
                ('año', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año')),
                ('tipo', models.CharField(choices=[('TURISMO', 'Turismo'), ('SUV', 'SUV'), ('FURGON', 'Furgón'), ('PICKUP', 'Pickup'), ('MOTO', 'Moto'), ('OTRO', 'Otro')], default='TURISMO', max_length=30)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='inventario.marca')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'unique_together': {('marca', 'nombre', 'año')},
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Stock Actual')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo')),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(default='unidad', max_length=20, verbose_name='Unidad de Medida')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repuestos', to='inventario.categoriarepuesto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Repuesto / Insumo',
                'verbose_name_plural': 'Repuestos / Insumos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('numero_serie', models.CharField(max_length=50, unique=True, verbose_name='Número de Serie (Chasis)')),
                ('matricula', models.CharField(blank=True, max_length=20, verbose_name='Matrícula')),
                ('color', models.CharField(blank=True, max_length=50)),
                ('kilometros', models.PositiveIntegerField(default=0, verbose_name='Kilómetros')),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('USADA', 'Usada'), ('CONSIGNACION', 'En Consignación'), ('VENDIDA', 'Vendida'), ('RESERVADA', 'Reservada'), ('BAJA', 'Dada de Baja')], default='NUEVA', max_length=15)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Costo (€)')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Venta (€)')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_venta', models.DateField(blank=True, null=True, verbose_name='Fecha de Venta')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='inventario.modelo')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_provistas', to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
    ]
