# Generated by Django 6.1 on 2026-08-21 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.CharField(choices=[('INFO', 'Información'), ('ALERTA', 'Alerta'), ('CRITICO', 'Crítico')], default='INFO', max_length=10)),
                ('modulo', models.CharField(choices=[('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('CAJA', 'Caja / Tesorería'), ('FINANCIERO', 'Financiero'), ('RRHH', 'RRHH'), ('INVENTARIO', 'Inventario'), ('ACCOUNTS', 'Usuarios / Accesos'), ('SISTEMA', 'Sistema')], max_length=15)),
                ('accion', models.CharField(max_length=200, verbose_name='Acción')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('objeto_tipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Objeto')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('datos_previos', models.JSONField(blank=True, null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos Nuevos')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Auditoría',
                'verbose_name_plural': 'Eventos de Auditoría',
                'ordering': ['-timestamp'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='ProgramaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Auditoría')),
                ('modulo_objetivo', models.CharField(choices=[('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('CAJA', 'Caja / Tesorería'), ('FINANCIERO', 'Financiero'), ('RRHH', 'RRHH'), ('INVENTARIO', 'Inventario'), ('ACCOUNTS', 'Usuarios / Accesos'), ('SISTEMA', 'Sistema')], max_length=15, verbose_name='Módulo a Auditar')),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada')),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=15)),
                ('objetivos', models.TextField(verbose_name='Objetivos de la Auditoría')),
                ('hallazgos', models.TextField(blank=True, verbose_name='Hallazgos')),
                ('recomendaciones', models.TextField(blank=True)),
                ('informe_generado', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_programadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programa de Auditoría',
                'verbose_name_plural': 'Programas de Auditoría',
                'ordering': ['fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='InformeAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('fecha_informe', models.DateField()),
                ('resumen_ejecutivo', models.TextField(verbose_name='Resumen Ejecutivo')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='BAJO', max_length=10)),
                ('acciones_requeridas', models.TextField(blank=True, verbose_name='Acciones Requeridas')),
                ('fecha_seguimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Seguimiento')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('programa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe', to='auditoria.programaauditoria')),
            ],
            options={
                'verbose_name': 'Informe de Auditoría',
                'verbose_name_plural': 'Informes de Auditoría',
                'ordering': ['-fecha_informe'],
            },
        ),
    ]
