# Generated by Django 6.1 on 2026-08-21 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('cif_nif', models.CharField(blank=True, max_length=20, verbose_name='CIF/NIF')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('web', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('moneda', models.CharField(default='EUR', max_length=3, verbose_name='Moneda')),
                ('modulo_ventas', models.BooleanField(default=True)),
                ('modulo_compras', models.BooleanField(default=True)),
                ('modulo_taller', models.BooleanField(default=True)),
                ('modulo_rrhh', models.BooleanField(default=True)),
                ('modulo_financiero', models.BooleanField(default=True)),
                ('alerta_proyeccion_minima', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Alerta cuando proyección baje de (€)')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
