# Generated by Django 6.1 on 2026-08-21 17:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código Cliente')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni_nie', models.CharField(blank=True, max_length=15, verbose_name='DNI/NIE')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('matricula_cliente', models.CharField(blank=True, max_length=20, verbose_name='Matrícula (si no está en sistema)')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PRESUPUESTADO', 'Presupuestado'), ('EN_CURSO', 'En Curso'), ('TERMINADO', 'Terminado'), ('FACTURADO', 'Facturado'), ('CANCELADO', 'Cancelado')], default='PRESUPUESTADO', max_length=15)),
                ('descripcion_trabajo', models.TextField(verbose_name='Descripción del Trabajo')),
                ('horas_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas de Mano de Obra')),
                ('precio_hora', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio por Hora (€)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_taller', to='ventas.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='inventario.unidad')),
            ],
            options={
                'verbose_name': 'Servicio de Taller',
                'verbose_name_plural': 'Servicios de Taller',
            },
        ),
        migrations.CreateModel(
            name='RepuestoUsadoEnServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.repuesto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_usados', to='ventas.serviciotaller')),
            ],
            options={
                'verbose_name': 'Repuesto Usado en Servicio',
                'verbose_name_plural': 'Repuestos Usados en Servicios',
            },
        ),
        migrations.CreateModel(
            name='VentaUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('fecha_venta', models.DateField(verbose_name='Fecha de Venta')),
                ('precio_acordado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Acordado (€)')),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Anticipo (€)')),
                ('monto_financiado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Financiado (€)')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('COMPLETO', 'Pagado Completo'), ('FINANCIADO', 'Financiado')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_unidades', to='ventas.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('unidad', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='venta', to='inventario.unidad')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta de Unidad',
                'verbose_name_plural': 'Ventas de Unidades',
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('numero_cuota', models.PositiveSmallIntegerField(verbose_name='N° Cuota')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (€)')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago Real')),
                ('pagado', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.ventaunidad')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Ventas',
                'ordering': ['venta', 'numero_cuota'],
                'unique_together': {('venta', 'numero_cuota')},
            },
        ),
    ]
