# Generated by Django 6.1 on 2026-08-29 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciotaller',
            name='costo_imputado_a_unidad',
            field=models.BooleanField(default=False, help_text='Solo ORI. Cuando True, el costo se sumó al precio_costo de la unidad.', verbose_name='Costo imputado a unidad'),
        ),
        migrations.AddField(
            model_name='serviciotaller',
            name='tipo',
            field=models.CharField(choices=[('OT', 'OT — Orden de Trabajo (cliente externo)'), ('ORI', 'ORI — Orden Reparación Interna (uso propio)')], default='OT', help_text='ORI = interno, nunca facturable, no genera movimiento de caja', max_length=3, verbose_name='Tipo de Orden'),
        ),
        migrations.AlterField(
            model_name='serviciotaller',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_taller', to='ventas.cliente'),
        ),
    ]
