# Generated by Django 6.1 on 2026-09-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_add_tipo_ori_to_servicio_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaunidad',
            name='tipo_financiacion',
            field=models.CharField(choices=[('CONTADO', 'Contado (pago íntegro)'), ('CUOTAS', 'Cuotas directas al concesionario'), ('BANCARIA', 'Financiación bancaria (banco paga al concesionario)'), ('PROPIA', 'Financiación propia del concesionario (largo plazo)')], default='CUOTAS', help_text='CONTADO: pago íntegro al momento. CUOTAS: cliente paga cuotas directas. BANCARIA: banco paga al concesionario de una vez. PROPIA: concesionario financia a largo plazo.', max_length=10, verbose_name='Tipo de Financiación'),
        ),
        migrations.AlterField(
            model_name='ventaunidad',
            name='monto_financiado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto a Financiar (€)'),
        ),
    ]
