# Generated by Django 6.1 on 2026-08-21 17:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligacionRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('SUELDO', 'Sueldo / Salario'), ('ALQUILER', 'Alquiler'), ('SUMINIST', 'Suministro (Luz, Gas, Agua, Internet)'), ('SEGUROS', 'Seguros'), ('OTROS', 'Otros gastos fijos')], max_length=10)),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dia_vencimiento', models.PositiveSmallIntegerField(help_text='Ej: 28 para el día 28 de cada mes', verbose_name='Día de vencimiento del mes')),
                ('referencia_empleado_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del Empleado (si es sueldo)')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Obligación Recurrente',
                'verbose_name_plural': 'Obligaciones Recurrentes',
            },
        ),
        migrations.CreateModel(
            name='ProyeccionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('fecha_calculo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Cálculo')),
                ('fecha_horizonte', models.DateField(verbose_name='Fecha Horizonte (proyección hasta...)')),
                ('saldo_caja_actual', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Saldo de Caja Actual (€)')),
                ('pagares_en_cartera', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Pagarés en Cartera — Total (€)')),
                ('saldo_bancos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Saldo Total en Bancos (€)')),
                ('cobros_previstos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Cobros Previstos (cuotas clientes) hasta el horizonte (€)')),
                ('pagos_proveedores_unidades', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Cuotas de Unidades a Pagar — hasta horizonte (€)')),
                ('pagos_proveedores_insumos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Pagos a Proveedores (insumos) — hasta horizonte (€)')),
                ('sueldos_previstos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sueldos a Pagar — hasta horizonte (€)')),
                ('servicios_previstos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Servicios (Luz, Gas, etc.) — hasta horizonte (€)')),
                ('total_activos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Activos (€)')),
                ('total_pasivos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Pasivos (€)')),
                ('posicion_neta', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Posición Neta (€)')),
                ('alerta_activa', models.BooleanField(default=False, verbose_name='¡Alerta! Proyección por debajo del umbral')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Proyección Financiera',
                'verbose_name_plural': 'Proyecciones Financieras',
                'ordering': ['-fecha_calculo'],
                'get_latest_by': 'fecha_calculo',
            },
        ),
    ]
