# Generated by Django 6.1 on 2026-08-21 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha del Cierre')),
                ('saldo_caja_apertura', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_ingresos', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_egresos', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_caja_cierre', models.DecimalField(decimal_places=2, max_digits=14)),
                ('operaciones_pendientes', models.PositiveSmallIntegerField(default=0, verbose_name='Operaciones Pendientes de Registro')),
                ('observaciones', models.TextField(blank=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_autorizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Cierre del Día',
                'verbose_name_plural': 'Cierres del Día',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=30, unique=True)),
                ('iban', models.CharField(blank=True, max_length=30)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('concepto', models.CharField(choices=[('CVU', 'Cobro Venta de Unidad'), ('CST', 'Cobro Servicio de Taller'), ('CCC', 'Cobro Cuota a Cliente'), ('PPU', 'Pago a Proveedor — Unidad'), ('PPI', 'Pago a Proveedor — Insumo'), ('PSU', 'Pago de Sueldo'), ('PSR', 'Pago de Servicio (Luz, Gas, etc.)'), ('DBA', 'Depósito en Banco'), ('EBA', 'Extracción de Banco'), ('OTR', 'Otro')], max_length=5, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto (€)')),
                ('fecha', models.DateField(verbose_name='Fecha del Movimiento')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('numero_documento', models.CharField(blank=True, max_length=50, verbose_name='N° Documento / Factura')),
                ('referencia_venta_id', models.PositiveIntegerField(blank=True, null=True)),
                ('referencia_compra_id', models.PositiveIntegerField(blank=True, null=True)),
                ('referencia_servicio_id', models.PositiveIntegerField(blank=True, null=True)),
                ('cerrado_en_dia', models.BooleanField(default=False, verbose_name='Incluido en cierre del día')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pagare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='N° de Pagaré')),
                ('emisor', models.CharField(max_length=200, verbose_name='Emisor / Librador')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (€)')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('CARTERA', 'En Cartera'), ('COBRADO', 'Cobrado'), ('PROTEST', 'Protestado'), ('CEDIDO', 'Cedido al Banco')], default='CARTERA', max_length=10)),
                ('referencia_venta_id', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Pagaré',
                'verbose_name_plural': 'Pagarés',
                'ordering': ['fecha_vencimiento'],
            },
        ),
    ]
