# Generated by Django 6.1 on 2026-08-21 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('cantidad_pedida', models.PositiveSmallIntegerField()),
                ('cantidad_recibida', models.PositiveSmallIntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Ítem de Orden de Compra',
                'verbose_name_plural': 'Ítems de Órdenes de Compra',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('numero_orden', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_pedido', models.DateField(verbose_name='Fecha del Pedido')),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada al Proveedor'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=10)),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('condiciones_pago', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Orden de Compra (Insumos)',
                'verbose_name_plural': 'Órdenes de Compra (Insumos)',
            },
        ),
        migrations.CreateModel(
            name='PagoCompraUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('numero_cuota', models.PositiveSmallIntegerField(verbose_name='N° Cuota')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (€)')),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('pagado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pago de Compra de Unidad',
                'verbose_name_plural': 'Pagos de Compras de Unidades',
                'ordering': ['compra', 'numero_cuota'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código Proveedor')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('cif_nif', models.CharField(blank=True, max_length=20, verbose_name='CIF/NIF')),
                ('tipo', models.CharField(choices=[('GRAN', 'Gran Proveedor (Marca Oficial)'), ('REP', 'Repuestos / Insumos'), ('SRV', 'Servicios Generales'), ('OTR', 'Otro')], default='REP', max_length=5)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('condiciones_pago', models.TextField(blank=True, verbose_name='Condiciones de Pago habituales')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de Crédito (€)')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='CompraUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar registros.', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('tipo_compra', models.CharField(choices=[('NUEVA', 'Unidad Nueva'), ('USADA', 'Unidad Usada'), ('CONSIG', 'En Consignación')], default='NUEVA', max_length=10)),
                ('fecha_compra', models.DateField(verbose_name='Fecha de Compra')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Compra (€)')),
                ('anticipo_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Anticipo Pagado (€)')),
                ('saldo_financiado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Financiado (€)')),
                ('numero_factura_proveedor', models.CharField(blank=True, max_length=50, verbose_name='N° Factura del Proveedor')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Compra de Unidad',
                'verbose_name_plural': 'Compras de Unidades',
            },
        ),
    ]
